/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.FurnitureIS.view;

import com.FurnitureIS.controller.algorithms.BinarySearch;
import com.FurnitureIS.controller.algorithms.InsertionSort;
import com.FurnitureIS.controller.algorithms.MergeSort;
import com.FurnitureIS.controller.algorithms.SelectionSort;
import java.awt.CardLayout;
import com.FurnitureIS.util.ValidationUtil;
import com.FurnitureIS.model.Furnituremodel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Kayosh Raj Pradha,23048672
 */
public class FurnitureIS extends javax.swing.JFrame {
    
    private List<Furnituremodel> furnitureList;
    private java.awt.CardLayout FormCardLayout;

    /**
     * Creates new form coursework
     */
    public FurnitureIS() {
        initComponents();
        initializeData();
        frameLayoutComponent();
    }
    private void frameLayoutComponent(){

        FormCardLayout = new CardLayout();
        getContentPane().setLayout(FormCardLayout);
        getContentPane().add(loginPanel,"login");
        getContentPane().add(pnlHome,"Home");

        showPanels("login");

    }
    private void showPanels(String Panel){
        FormCardLayout.show(getContentPane(), Panel);
    }

    private void initializeData() {
        furnitureList = new ArrayList();
        
        // Registering sample students
        registerFurniture(new Furnituremodel("chr1000001", "ram", "chair","fantech","Polymer"));
        registerFurniture(new Furnituremodel("tbl1000002", "shyam", "table","fantech","Engineered Wood"));
        registerFurniture(new Furnituremodel("chr1000003", "sitaram", "chair","fantech","Forged Metal"));
        registerFurniture(new Furnituremodel("tbl1000004", "asmita", "table","fantech","Marble"));
        registerFurniture(new Furnituremodel("sfa1000005", "hari", "sofa","chicha","Engineered Wood"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHome = new javax.swing.JPanel();
        homeBodyPnl = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbPHome = new javax.swing.JTabbedPane();
        pnlHomeInfo = new javax.swing.JPanel();
        lblHomeCover = new javax.swing.JLabel();
        pnlHomeTitle = new javax.swing.JPanel();
        lblLive = new javax.swing.JLabel();
        lblIN = new javax.swing.JLabel();
        lblStyle = new javax.swing.JLabel();
        Lbl2001 = new javax.swing.JLabel();
        lblbedroom = new javax.swing.JLabel();
        llbImgBEd = new javax.swing.JLabel();
        llbImgSofa = new javax.swing.JLabel();
        llbImgBEd2 = new javax.swing.JLabel();
        lblsofa = new javax.swing.JLabel();
        lblTable = new javax.swing.JLabel();
        llbImgBEd1 = new javax.swing.JLabel();
        llbImgBEd3 = new javax.swing.JLabel();
        llbImgBEd4 = new javax.swing.JLabel();
        lblChair = new javax.swing.JLabel();
        lblDining = new javax.swing.JLabel();
        lblWardrobe = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        spTableInfo = new javax.swing.JScrollPane();
        tblFurnitureInfo = new javax.swing.JTable();
        pnlForm = new javax.swing.JPanel();
        lblFurManagement = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        tfType = new javax.swing.JTextField();
        tfBrand = new javax.swing.JTextField();
        tfFurnitureId = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        cbMaterial = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        cbdropsort = new javax.swing.JComboBox<>();
        tfSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        pnlAboutus = new javax.swing.JPanel();
        lblAboutUs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAbout1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAbout2 = new javax.swing.JTextArea();
        lblContact = new javax.swing.JLabel();
        lblmail = new javax.swing.JLabel();
        lblphone = new javax.swing.JLabel();
        lblfollow = new javax.swing.JLabel();
        lblinsta = new javax.swing.JLabel();
        lblFacebook = new javax.swing.JLabel();
        lblTwitter = new javax.swing.JLabel();
        lblOwner = new javax.swing.JLabel();
        lbimgOwner = new javax.swing.JLabel();
        lblneil = new javax.swing.JLabel();
        pnlheader = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        loginPanel = new javax.swing.JPanel();
        pnlLog = new javax.swing.JPanel();
        lblLoginSubTitle = new javax.swing.JLabel();
        txtFldLoginUsername = new javax.swing.JTextField();
        pwdFldLogin = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblLoginTitle = new javax.swing.JLabel();
        lblLoginError = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblEst = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblCname = new javax.swing.JLabel();
        lblCname1 = new javax.swing.JLabel();

        homeBodyPnl.setBackground(new java.awt.Color(0, 102, 102));
        homeBodyPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 3, true));

        jScrollPane3.setMaximumSize(new java.awt.Dimension(882, 804));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(900, 900));

        tbPHome.setBackground(new java.awt.Color(0, 102, 102));
        tbPHome.setForeground(new java.awt.Color(255, 255, 204));
        tbPHome.setPreferredSize(new java.awt.Dimension(852, 900));

        pnlHomeInfo.setBackground(new java.awt.Color(0, 102, 102));
        pnlHomeInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 3, true));
        pnlHomeInfo.setPreferredSize(new java.awt.Dimension(852, 800));

        lblHomeCover.setForeground(new java.awt.Color(255, 255, 204));
        lblHomeCover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/FurnitureIS/resources/home cover (1).jpg"))); // NOI18N
        lblHomeCover.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 3, true));

        pnlHomeTitle.setBackground(new java.awt.Color(0, 102, 102));
        pnlHomeTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 3, true));

        lblLive.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblLive.setForeground(new java.awt.Color(255, 255, 204));
        lblLive.setText("LIVE");

        lblIN.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblIN.setForeground(new java.awt.Color(255, 255, 204));
        lblIN.setText("IN");

        lblStyle.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblStyle.setForeground(new java.awt.Color(255, 255, 204));
        lblStyle.setText("STYLE");

        Lbl2001.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Lbl2001.setForeground(new java.awt.Color(255, 255, 204));
        Lbl2001.setText("Since 2001");

        javax.swing.GroupLayout pnlHomeTitleLayout = new javax.swing.GroupLayout(pnlHomeTitle);
        pnlHomeTitle.setLayout(pnlHomeTitleLayout);
        pnlHomeTitleLayout.setHorizontalGroup(
            pnlHomeTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeTitleLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(pnlHomeTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeTitleLayout.createSequentialGroup()
                        .addComponent(lblLive, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIN, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeTitleLayout.createSequentialGroup()
                        .addGroup(pnlHomeTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHomeTitleLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Lbl2001, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))))
        );
        pnlHomeTitleLayout.setVerticalGroup(
            pnlHomeTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHomeTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLive, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIN, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lbl2001, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblbedroom.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblbedroom.setForeground(new java.awt.Color(255, 255, 204));
        lblbedroom.setText("BeedRoom");

        llbImgBEd.setForeground(new java.awt.Color(0, 51, 51));
        llbImgBEd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/FurnitureIS/resources/table (1).jpg"))); // NOI18N
        llbImgBEd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 3, true));

        llbImgSofa.setForeground(new java.awt.Color(0, 51, 51));
        llbImgSofa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/FurnitureIS/resources/sofa (1).jpg"))); // NOI18N
        llbImgSofa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 3, true));

        llbImgBEd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/FurnitureIS/resources/bed (1).jpg"))); // NOI18N
        llbImgBEd2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 3, true));

        lblsofa.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblsofa.setForeground(new java.awt.Color(255, 255, 204));
        lblsofa.setText("Sofa");

        lblTable.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblTable.setForeground(new java.awt.Color(255, 255, 204));
        lblTable.setText("Office ");

        llbImgBEd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/FurnitureIS/resources/chair (1).jpg"))); // NOI18N
        llbImgBEd1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 3, true));

        llbImgBEd3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/FurnitureIS/resources/dining (1).jpg"))); // NOI18N
        llbImgBEd3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 3, true));

        llbImgBEd4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/FurnitureIS/resources/wardrobe (1).jpg"))); // NOI18N
        llbImgBEd4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 3, true));

        lblChair.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblChair.setForeground(new java.awt.Color(255, 255, 204));
        lblChair.setText("Chair");

        lblDining.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblDining.setForeground(new java.awt.Color(255, 255, 204));
        lblDining.setText("Dining");

        lblWardrobe.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblWardrobe.setForeground(new java.awt.Color(255, 255, 204));
        lblWardrobe.setText("Wardrobe");

        javax.swing.GroupLayout pnlHomeInfoLayout = new javax.swing.GroupLayout(pnlHomeInfo);
        pnlHomeInfo.setLayout(pnlHomeInfoLayout);
        pnlHomeInfoLayout.setHorizontalGroup(
            pnlHomeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeInfoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlHomeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlHomeInfoLayout.createSequentialGroup()
                        .addComponent(lblHomeCover)
                        .addGap(0, 0, 0)
                        .addComponent(pnlHomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeInfoLayout.createSequentialGroup()
                        .addGroup(pnlHomeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(llbImgBEd)
                            .addComponent(llbImgBEd4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlHomeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(llbImgBEd2)
                            .addComponent(llbImgBEd1))
                        .addGap(51, 51, 51)
                        .addGroup(pnlHomeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(llbImgBEd3)
                            .addComponent(llbImgSofa))))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(pnlHomeInfoLayout.createSequentialGroup()
                .addGroup(pnlHomeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeInfoLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lblWardrobe)
                        .addGap(198, 198, 198)
                        .addComponent(lblChair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDining))
                    .addGroup(pnlHomeInfoLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(lblTable)
                        .addGap(181, 181, 181)
                        .addComponent(lblbedroom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblsofa)))
                .addGap(165, 165, 165))
        );
        pnlHomeInfoLayout.setVerticalGroup(
            pnlHomeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHomeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlHomeTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHomeCover, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHomeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(llbImgBEd2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(llbImgBEd, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(llbImgSofa, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHomeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblbedroom)
                        .addComponent(lblsofa))
                    .addComponent(lblTable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHomeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(llbImgBEd3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(llbImgBEd1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(llbImgBEd4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHomeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWardrobe)
                    .addComponent(lblChair)
                    .addComponent(lblDining))
                .addGap(0, 305, Short.MAX_VALUE))
        );

        tbPHome.addTab("HOME", pnlHomeInfo);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 3, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(852, 500));

        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("Furniture Information");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));

        spTableInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));

        tblFurnitureInfo.setBackground(new java.awt.Color(0, 51, 51));
        tblFurnitureInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblFurnitureInfo.setForeground(new java.awt.Color(255, 255, 204));
        tblFurnitureInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Furniture Id", "Name", "Type", "Brand", "Material"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFurnitureInfo.getTableHeader().setReorderingAllowed(false);
        spTableInfo.setViewportView(tblFurnitureInfo);

        pnlForm.setBackground(new java.awt.Color(0, 102, 102));
        pnlForm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 3, true));
        pnlForm.setForeground(new java.awt.Color(255, 255, 204));

        lblFurManagement.setForeground(new java.awt.Color(255, 255, 204));
        lblFurManagement.setText("Furniture Mangemont Form");
        lblFurManagement.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));

        tfname.setBackground(new java.awt.Color(0, 51, 51));
        tfname.setForeground(new java.awt.Color(255, 255, 204));
        tfname.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 204))); // NOI18N

        tfType.setBackground(new java.awt.Color(0, 51, 51));
        tfType.setForeground(new java.awt.Color(255, 255, 204));
        tfType.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 204))); // NOI18N

        tfBrand.setBackground(new java.awt.Color(0, 51, 51));
        tfBrand.setForeground(new java.awt.Color(255, 255, 204));
        tfBrand.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Brand", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 204))); // NOI18N

        tfFurnitureId.setBackground(new java.awt.Color(0, 51, 51));
        tfFurnitureId.setForeground(new java.awt.Color(255, 255, 204));
        tfFurnitureId.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Furniture ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 204))); // NOI18N
        tfFurnitureId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFurnitureIdActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 51, 51));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 204));
        btnAdd.setText("Add");
        btnAdd.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(0, 51, 51));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 204));
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 51, 51));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 204));
        btnDelete.setText("Delete");
        btnDelete.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        cbMaterial.setBackground(new java.awt.Color(0, 51, 51));
        cbMaterial.setForeground(new java.awt.Color(255, 255, 204));
        cbMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Engineered Wood", "Forged Metal", "Polymer", "Marble" }));
        cbMaterial.setToolTipText("");
        cbMaterial.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Material", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 204))); // NOI18N
        cbMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaterialActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 51, 51));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 204));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        cbdropsort.setBackground(new java.awt.Color(0, 51, 51));
        cbdropsort.setForeground(new java.awt.Color(255, 255, 204));
        cbdropsort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "FurnitureID", "Type" }));
        cbdropsort.setToolTipText("");
        cbdropsort.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sort By:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 204))); // NOI18N
        cbdropsort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbdropsortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFormLayout = new javax.swing.GroupLayout(pnlForm);
        pnlForm.setLayout(pnlFormLayout);
        pnlFormLayout.setHorizontalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormLayout.createSequentialGroup()
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFormLayout.createSequentialGroup()
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbMaterial, 0, 149, Short.MAX_VALUE)
                                    .addComponent(tfFurnitureId))
                                .addGap(42, 42, 42)
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlFormLayout.createSequentialGroup()
                                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlFormLayout.createSequentialGroup()
                                .addComponent(lblFurManagement)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbdropsort, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tfType, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(tfBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        pnlFormLayout.setVerticalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbdropsort)
                    .addComponent(lblFurManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfname)
                    .addComponent(tfFurnitureId, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfType, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        tfSearch.setForeground(new java.awt.Color(0, 51, 51));
        tfSearch.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)), javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51))));
        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });

        lblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/FurnitureIS/resources/search.png"))); // NOI18N
        lblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTableInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTableInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );

        tbPHome.addTab("ADMIN CONTROL", jPanel2);

        pnlAboutus.setBackground(new java.awt.Color(0, 102, 102));
        pnlAboutus.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)), javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51))));

        lblAboutUs.setBackground(new java.awt.Color(0, 51, 51));
        lblAboutUs.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        lblAboutUs.setForeground(new java.awt.Color(255, 255, 204));
        lblAboutUs.setText("About US");

        taAbout1.setEditable(false);
        taAbout1.setBackground(new java.awt.Color(0, 51, 51));
        taAbout1.setColumns(20);
        taAbout1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        taAbout1.setForeground(new java.awt.Color(255, 255, 204));
        taAbout1.setRows(2);
        taAbout1.setText("We take pride in being one of Nepal's biggest importers and merchants of furniture. Since 2001, we have been \nproviding our clients with furniture that better fits their lifestyles through our four showrooms and two warehouses. \nWe import high-quality furniture from a number of nations, including Malaysia, China, Vietnam, and Thailand.\nTo ensure that we have enough furniture on hand to meet demand,we maintain the greatest inventory. We teach \nour employees to be the best at giving our clients long-term commitment, timely delivery, expert advise, and the \nhighest level of customer satisfaction because we really believe that we are what we are because of our customers.");
        taAbout1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 0), new java.awt.Color(51, 51, 0), new java.awt.Color(51, 51, 0), new java.awt.Color(51, 51, 0)), javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51))));
        jScrollPane1.setViewportView(taAbout1);

        taAbout2.setEditable(false);
        taAbout2.setBackground(new java.awt.Color(0, 51, 51));
        taAbout2.setColumns(20);
        taAbout2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        taAbout2.setForeground(new java.awt.Color(255, 255, 204));
        taAbout2.setRows(2);
        taAbout2.setText("\"We strive to provide our customers with wide selection of furniture and household \ndecorative tems that are well designed, functional, practical, comfortable and have \nbest value for money.\"");
        taAbout2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)), javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51))));
        jScrollPane2.setViewportView(taAbout2);

        lblContact.setForeground(new java.awt.Color(255, 255, 204));
        lblContact.setText("Contact Us at:");

        lblmail.setForeground(new java.awt.Color(255, 255, 204));
        lblmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/FurnitureIS/resources/email.png"))); // NOI18N
        lblmail.setText(" sales@furnitureworld.com.np");

        lblphone.setForeground(new java.awt.Color(255, 255, 204));
        lblphone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/FurnitureIS/resources/phone-call.png"))); // NOI18N
        lblphone.setText("015432167");

        lblfollow.setForeground(new java.awt.Color(255, 255, 204));
        lblfollow.setText("Follow Us at: ");

        lblinsta.setForeground(new java.awt.Color(255, 255, 204));
        lblinsta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/FurnitureIS/resources/instagram.png"))); // NOI18N
        lblinsta.setText("FurnitureWorld");

        lblFacebook.setForeground(new java.awt.Color(255, 255, 204));
        lblFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/FurnitureIS/resources/facebook.png"))); // NOI18N
        lblFacebook.setText("FurnitureWorld");

        lblTwitter.setForeground(new java.awt.Color(255, 255, 204));
        lblTwitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/FurnitureIS/resources/twitter.png"))); // NOI18N
        lblTwitter.setText("FurnitureWorld");

        lblOwner.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOwner.setForeground(new java.awt.Color(255, 255, 204));
        lblOwner.setText("Owner of Furniture world");

        lbimgOwner.setForeground(new java.awt.Color(255, 255, 204));
        lbimgOwner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/FurnitureIS/resources/neil caffrey (1).jpg"))); // NOI18N
        lbimgOwner.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51))));

        lblneil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblneil.setForeground(new java.awt.Color(255, 255, 204));
        lblneil.setText("MR. Neil Caffrey ");

        javax.swing.GroupLayout pnlAboutusLayout = new javax.swing.GroupLayout(pnlAboutus);
        pnlAboutus.setLayout(pnlAboutusLayout);
        pnlAboutusLayout.setHorizontalGroup(
            pnlAboutusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAboutusLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(pnlAboutusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAboutusLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(lblAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(355, Short.MAX_VALUE))
                    .addGroup(pnlAboutusLayout.createSequentialGroup()
                        .addGroup(pnlAboutusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblContact)
                            .addComponent(lblfollow))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlAboutusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblinsta)
                            .addComponent(lblTwitter)
                            .addComponent(lblphone, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFacebook)
                            .addComponent(lblmail, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                        .addGroup(pnlAboutusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutusLayout.createSequentialGroup()
                                .addComponent(lbimgOwner)
                                .addGap(193, 193, 193))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutusLayout.createSequentialGroup()
                                .addComponent(lblneil, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(178, 178, 178))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
            .addGroup(pnlAboutusLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pnlAboutusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAboutusLayout.setVerticalGroup(
            pnlAboutusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAboutusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOwner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAboutusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAboutusLayout.createSequentialGroup()
                        .addGroup(pnlAboutusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmail)
                            .addComponent(lblContact))
                        .addGap(7, 7, 7)
                        .addComponent(lblphone)
                        .addGap(26, 26, 26)
                        .addGroup(pnlAboutusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblfollow)
                            .addComponent(lblinsta)))
                    .addGroup(pnlAboutusLayout.createSequentialGroup()
                        .addGroup(pnlAboutusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbimgOwner)
                            .addComponent(lblTwitter))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAboutusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFacebook)
                            .addComponent(lblneil, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(115, 309, Short.MAX_VALUE))
        );

        tbPHome.addTab("ABOUT US", pnlAboutus);

        jScrollPane3.setViewportView(tbPHome);

        javax.swing.GroupLayout homeBodyPnlLayout = new javax.swing.GroupLayout(homeBodyPnl);
        homeBodyPnl.setLayout(homeBodyPnlLayout);
        homeBodyPnlLayout.setHorizontalGroup(
            homeBodyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeBodyPnlLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homeBodyPnlLayout.setVerticalGroup(
            homeBodyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeBodyPnlLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlheader.setBackground(new java.awt.Color(0, 51, 51));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/FurnitureIS/resources/furniture.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("FURNITURE WORLD, WHERE COMFORT MEETS STYLE");

        btnLogOut.setBackground(new java.awt.Color(0, 102, 102));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 204));
        btnLogOut.setText("LogOut");
        btnLogOut.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
        });
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlheaderLayout = new javax.swing.GroupLayout(pnlheader);
        pnlheader.setLayout(pnlheaderLayout);
        pnlheaderLayout.setHorizontalGroup(
            pnlheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlheaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        pnlheaderLayout.setVerticalGroup(
            pnlheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlheaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo)
                    .addGroup(pnlheaderLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(pnlheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlheader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homeBodyPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addComponent(pnlheader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeBodyPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        loginPanel.setBackground(new java.awt.Color(51, 51, 51));

        pnlLog.setBackground(new java.awt.Color(0, 102, 102));

        lblLoginSubTitle.setBackground(new java.awt.Color(234, 192, 32));
        lblLoginSubTitle.setForeground(new java.awt.Color(255, 255, 204));
        lblLoginSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginSubTitle.setText("Please enter your login details below.");

        txtFldLoginUsername.setBackground(new java.awt.Color(0, 102, 102));
        txtFldLoginUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFldLoginUsername.setForeground(new java.awt.Color(255, 255, 204));
        txtFldLoginUsername.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 2), "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 204))); // NOI18N
        txtFldLoginUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldLoginUsernameActionPerformed(evt);
            }
        });

        pwdFldLogin.setBackground(new java.awt.Color(0, 102, 102));
        pwdFldLogin.setForeground(new java.awt.Color(255, 255, 204));
        pwdFldLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 2), "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 204))); // NOI18N
        pwdFldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdFldLoginActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(0, 51, 51));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 204));
        btnLogin.setText("Login");
        btnLogin.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblLoginTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLoginTitle.setForeground(new java.awt.Color(255, 255, 204));
        lblLoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginTitle.setText("Sign in to Furniture World");

        lblLoginError.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout pnlLogLayout = new javax.swing.GroupLayout(pnlLog);
        pnlLog.setLayout(pnlLogLayout);
        pnlLogLayout.setHorizontalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogLayout.createSequentialGroup()
                .addGap(0, 45, Short.MAX_VALUE)
                .addGroup(pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogLayout.createSequentialGroup()
                        .addComponent(lblLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogLayout.createSequentialGroup()
                        .addComponent(lblLoginError, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
            .addGroup(pnlLogLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdFldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLoginSubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLogLayout.setVerticalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblLoginError, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLoginSubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(txtFldLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pwdFldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/FurnitureIS/resources/chair login.png"))); // NOI18N

        lblEst.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEst.setForeground(new java.awt.Color(242, 242, 242));
        lblEst.setText("est.");

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(242, 242, 242));
        lblDate.setText("2001");

        lblCname.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblCname.setForeground(new java.awt.Color(242, 242, 242));
        lblCname.setText("WHERE COMFORT MEETS STYLE");

        lblCname1.setFont(new java.awt.Font("SimSun", 1, 36)); // NOI18N
        lblCname1.setForeground(new java.awt.Color(242, 242, 242));
        lblCname1.setText("FURNITURE WORLD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCname1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblEst)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblDate))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblCname, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(62, 62, 62)
                .addComponent(lblCname1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lblCname, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addComponent(pnlLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   
    private void registerFurniture(Furnituremodel furniture) {
        furnitureList.add(furniture);
        
        DefaultTableModel model = (DefaultTableModel) tblFurnitureInfo.getModel();
        model.addRow(new Object[]{
            furniture.getFurnitureID(), furniture.getName(), furniture.getType(),
            furniture.getBrand(), furniture.getMaterial()
        });
    }

        
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtFldLoginUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldLoginUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldLoginUsernameActionPerformed

    private void pwdFldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdFldLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdFldLoginActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        lblSearchMouseClicked(null);
    }//GEN-LAST:event_tfSearchActionPerformed
    
    
    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
    String username = txtFldLoginUsername.getText();
        String password = new String(pwdFldLogin.getPassword());

        // Check if username or password is empty
        if (username.isEmpty() || password.isEmpty()) {
            lblLoginError.setText("Fill your username and password.");
        } // Check if username and password are incorrect
        else if (!username.equals("admin") || !password.equals("admin")) {
            lblLoginError.setText("Username and password mismatch.");
        } // If credentials are correct, proceed to load the main screen
        else {
            lblLoginError.setText(""); // Clear any previous error messages
            showPanels("Home"); // Load the main screen
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
        showPanels("login");// TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        tfFurnitureId.setText("");
        tfname.setText("");
        tfType.setText("");
        tfBrand.setText("");
         
// TODO add your handling code here:
    }//GEN-LAST:event_btnClearMouseClicked

    private void cbMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMaterialActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
                                        
    String ID = tfFurnitureId.getText();
    String Name = tfname.getText();
    String Type = tfType.getText();
    String Brand = tfBrand.getText();
    String Material = (String) cbMaterial.getSelectedItem();

    // Check for empty fields
    if (ValidationUtil.isNullOrEmpty(ID) ||
        ValidationUtil.isNullOrEmpty(Name) ||
        ValidationUtil.isNullOrEmpty(Type) ||
        ValidationUtil.isNullOrEmpty(Brand) ||
        ValidationUtil.isNullOrEmpty(Material)) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Please fill out all fields.", 
            "Validation Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Check for duplicate ID
    for (Furnituremodel furniture : furnitureList) {
        if (furniture.getFurnitureID().equals(ID)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Furniture ID already exists. Please use a unique ID.", 
                "Duplicate ID Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

    // Validatin individual fields
    if (!ValidationUtil.isValidFurnitureId(ID)) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Furniture ID must start with letters and end with 7 digits.", 
            "Validation Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!ValidationUtil.isValidName(Name)) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Name must only contain alphabets.", 
            "Validation Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!ValidationUtil.isValidType(Type)) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Type must only contain alphabets.", 
            "Validation Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!ValidationUtil.isValidBrand(Brand)) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Brand must only contain alphabets.", 
            "Validation Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Default selected material if none is chosen
    if (ValidationUtil.isNullOrEmpty(Material)) {
        Material = "Engineered Wood";
    }

    // Create Furniture object
    Furnituremodel furniture = new Furnituremodel(ID, Name, Type, Brand, Material);
    registerFurniture(furniture);

    // Show success message
    javax.swing.JOptionPane.showMessageDialog(this, 
        "Furniture item added successfully!", 
        "Success", 
        JOptionPane.INFORMATION_MESSAGE);
                                    

    }//GEN-LAST:event_btnAddMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
       int selectedRow = tblFurnitureInfo.getSelectedRow(); 

    if (selectedRow >= 0) {
        
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this item?",
            "Confirm Deletion",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            furnitureList.remove(selectedRow);

            // Remove the row from the table
            DefaultTableModel model = (DefaultTableModel) tblFurnitureInfo.getModel();
            model.removeRow(selectedRow);

            lblLoginError.setText(""); 
            javax.swing.JOptionPane.showMessageDialog(this, "Item deleted successfully.");
        }
    } else {
        
        javax.swing.JOptionPane.showMessageDialog(this, 
                "\"Please select a row to delete.", 
                "Validation Error", 
                JOptionPane.ERROR_MESSAGE);
            
    } // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void tfFurnitureIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFurnitureIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFurnitureIdActionPerformed

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblFurnitureInfo.getSelectedRow(); 

    if (selectedRow >= 0) {
        // Fetch new details from input fields
        String updatedID = tfFurnitureId.getText();
        String updatedName = tfname.getText();
        String updatedType = tfType.getText();
        String updatedBrand = tfBrand.getText();
        String updatedMaterial = (String) cbMaterial.getSelectedItem();

        // Validation for updated details
        if (ValidationUtil.isNullOrEmpty(updatedID) ||
            ValidationUtil.isNullOrEmpty(updatedName) ||
            ValidationUtil.isNullOrEmpty(updatedType) ||
            ValidationUtil.isNullOrEmpty(updatedBrand) ||
            ValidationUtil.isNullOrEmpty(updatedMaterial)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Please fill out all fields.", 
                "Validation Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!ValidationUtil.isValidFurnitureId(updatedID)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Furniture ID must start with letters and end with 7 digits.", 
                "Validation Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!ValidationUtil.isValidName(updatedName)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Name must only contain alphabets.", 
                "Validation Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!ValidationUtil.isValidType(updatedType)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Type must only contain alphabets.", 
                "Validation Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!ValidationUtil.isValidBrand(updatedBrand)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Brand must only contain alphabets.", 
                "Validation Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Update the furniture item in the list
        Furnituremodel furniture = furnitureList.get(selectedRow);
        furniture.setFurnitureID(updatedID);
        furniture.setName(updatedName);
        furniture.setType(updatedType);
        furniture.setBrand(updatedBrand);
        furniture.setMaterial(updatedMaterial);

        // Update the table row
        DefaultTableModel model = (DefaultTableModel) tblFurnitureInfo.getModel();
        model.setValueAt(updatedID, selectedRow, 0);
        model.setValueAt(updatedName, selectedRow, 1);
        model.setValueAt(updatedType, selectedRow, 2);
        model.setValueAt(updatedBrand, selectedRow, 3);
        model.setValueAt(updatedMaterial, selectedRow, 4);

        // Show success message
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Furniture item updated successfully!", 
            "Success", 
            JOptionPane.INFORMATION_MESSAGE);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Please select a row to update.", 
            "Update Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void lblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseClicked
         String searchValue = tfSearch.getText().trim(); // Get input value from the search text field

    if (searchValue.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a Name to search.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Ensure the list is sorted by Name before performing binary search
    SelectionSort selectionSort = new SelectionSort();
    selectionSort.performSelectionSort(furnitureList);

    // Perform binary search
    BinarySearch binarySearch = new BinarySearch();
    Furnituremodel result = binarySearch.searchByName(searchValue, furnitureList, 0, furnitureList.size() - 1);

    // Display the result
    if (result != null) {
        JOptionPane.showMessageDialog(this,
                "Furniture Found:\n" +
                        "FurnitureID: " + result.getFurnitureID() + "\n" +
                        "Name: " + result.getName() + "\n" +
                        "Type: " + result.getType() + "\n" +
                        "Brand: " + result.getBrand() + "\n" +
                        "Material: " + result.getMaterial(),
                "Search Result",
                JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Furniture with Name '" + searchValue + "' not found.", "Search Result", JOptionPane.WARNING_MESSAGE);
    }

    }//GEN-LAST:event_lblSearchMouseClicked

    private void cbdropsortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbdropsortActionPerformed
                                               
    // Get selected sorting attribute
                                              
    String selectedOption = (String) cbdropsort.getSelectedItem();
    SelectionSort selectionSort = new SelectionSort();
    InsertionSort insertionSort = new InsertionSort();
    MergeSort mergeSort = new MergeSort();

    switch (selectedOption.trim()) {
        case "Name":
            selectionSort.performSelectionSort(furnitureList); // Sort by Name
            break;

        case "FurnitureID":
           
            // Sorting FurnitureList by FurnitureID
            insertionSort.performInsertionSortByFurnitureID(furnitureList);

            // Aadmin
            
            break;

        case "Type":
            mergeSort.performMergeSortByType(furnitureList); // Sort by Type
            break;

        default:
            return;
    }

    // Refresh table after sorting
    DefaultTableModel furnitureTableModel = (DefaultTableModel) tblFurnitureInfo.getModel();
    furnitureTableModel.setRowCount(0); // Clear the table

    // Populate the table with sorted data
    furnitureList.forEach(element -> {
        Object[] furnitureData = {
            element.getFurnitureID(),
            element.getName(),
            element.getType(),
            element.getBrand(),
            element.getMaterial(),
        };
        furnitureTableModel.addRow(furnitureData);
    });

    
  

    }//GEN-LAST:event_cbdropsortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FurnitureIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FurnitureIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FurnitureIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FurnitureIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FurnitureIS().setVisible(true);
        });
    }
    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl2001;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbMaterial;
    private javax.swing.JComboBox<String> cbdropsort;
    private javax.swing.JPanel homeBodyPnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbimgOwner;
    private javax.swing.JLabel lblAboutUs;
    private javax.swing.JLabel lblChair;
    private javax.swing.JLabel lblCname;
    private javax.swing.JLabel lblCname1;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDining;
    private javax.swing.JLabel lblEst;
    private javax.swing.JLabel lblFacebook;
    private javax.swing.JLabel lblFurManagement;
    private javax.swing.JLabel lblHomeCover;
    private javax.swing.JLabel lblIN;
    private javax.swing.JLabel lblLive;
    private javax.swing.JLabel lblLoginError;
    private javax.swing.JLabel lblLoginSubTitle;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblOwner;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblStyle;
    private javax.swing.JLabel lblTable;
    private javax.swing.JLabel lblTwitter;
    private javax.swing.JLabel lblWardrobe;
    private javax.swing.JLabel lblbedroom;
    private javax.swing.JLabel lblfollow;
    private javax.swing.JLabel lblinsta;
    private javax.swing.JLabel lblmail;
    private javax.swing.JLabel lblneil;
    private javax.swing.JLabel lblphone;
    private javax.swing.JLabel lblsofa;
    private javax.swing.JLabel llbImgBEd;
    private javax.swing.JLabel llbImgBEd1;
    private javax.swing.JLabel llbImgBEd2;
    private javax.swing.JLabel llbImgBEd3;
    private javax.swing.JLabel llbImgBEd4;
    private javax.swing.JLabel llbImgSofa;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel pnlAboutus;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlHomeInfo;
    private javax.swing.JPanel pnlHomeTitle;
    private javax.swing.JPanel pnlLog;
    private javax.swing.JPanel pnlheader;
    private javax.swing.JPasswordField pwdFldLogin;
    private javax.swing.JScrollPane spTableInfo;
    private javax.swing.JTextArea taAbout1;
    private javax.swing.JTextArea taAbout2;
    private javax.swing.JTabbedPane tbPHome;
    private javax.swing.JTable tblFurnitureInfo;
    private javax.swing.JTextField tfBrand;
    private javax.swing.JTextField tfFurnitureId;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfType;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField txtFldLoginUsername;
    // End of variables declaration//GEN-END:variables
}
